mode = "dark"
accent = "#C48B64"
selection = "#493428"
selection_foreground = "#F0DFD0"
selection_background = "#493428"
muted = "#B49B87"
background = "#171717"
dark_background = "#101010"
darker_background = "#0A0A0A"
lighter_background = "#24201E"
foreground = "#E2CDBC"
dark_foreground = "#B49B87"
light_foreground = "#CBA98F"
bright_foreground = "#F0DFD0"
hyprland_active_border = "#C48B64"
hyprland_inactive_border = "#594335"
red = "#E2CDBC"
green = "#C48B64"
yellow = "#CBA98F"
orange = "#CBA98F"
blue = "#C48B64"
magenta = "#E2CDBC"
cyan = "#B49B87"
brown = "#B49B87"
bright_red = "#F0DFD0"
bright_green = "#E2CDBC"
bright_yellow = "#F0DFD0"
bright_blue = "#CBA98F"
bright_magenta = "#E2CDBC"
bright_cyan = "#C48B64"
